### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'ndim'

### ISSUE THREAD

**Issue by ghost** [adobe-research/MakeItTalk#3]
Traceback (most recent call last):
  File "main_end2end.py", line 73, in <module>
    shapes = predictor.get_landmarks(img)
  File "/usr/local/lib/python3.6/dist-packages/face_alignment/api.py", line 107, in get_landmarks
    return self.get_landmarks_from_image(image_or_path, detected_faces)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/face_alignment/api.py", line 134, in get_landmarks_from_image
    if image.ndim == 2:
AttributeError: 'NoneType' object has no attribute 'ndim'

**Comment by yzhou359** [comment]
It looks it didn't find the portrait image. Could you please check whether you put the image in the `examples` folder? or is the args for `--jpg <you_image_name>` correct?

**Comment by ghost** [comment]
@yzhou359 I tried both --jpg obama and without the jpg argument it went ahead and got the other error
Traceback (most recent call last):
File "main_end2end.py", line 150, in
model = Audio2landmark_model(opt_parser, jpg_shape=shape_3d)
File "/content/MakeItTalk/src/approaches/train_audio2landmark.py", line 81, in init
with open(os.path.join('examples', 'dump', 'emb.pickle'), 'rb') as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'examples/dump/emb.pickle'

**Comment by yzhou359** [comment]
Please check the latest README. There is a link for the emb.pickle in the latest commit from my forked version.

**Comment by ghost** [comment]
@yzhou359 thanks got it working!
