### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'examples/dump/celeb_withrot_val_au.pickle'

### ISSUE THREAD

**Issue by ghost** [adobe-research/MakeItTalk#4]
Traceback (most recent call last):
  File "main_end2end.py", line 150, in <module>
    model = Audio2landmark_model(opt_parser, jpg_shape=shape_3d)
  File "/content/MakeItTalk/src/approaches/train_audio2landmark.py", line 85, in __init__
    num_window_step=1)
  File "/content/MakeItTalk/src/dataset/audio2landmark/audio2landmark_dataset.py", line 33, in __init__
    with open(os.path.join(self.dump_dir, '{}_{}_au.pickle'.format(dump_name, status)), 'rb') as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'examples/dump/celeb_withrot_val_au.pickle'

**Comment by ghost** [comment]
after latest change now getting
Traceback (most recent call last):
  File "main_end2end.py", line 150, in <module>
    model = Audio2landmark_model(opt_parser, jpg_shape=shape_3d)
  File "/content/MakeItTalk/src/approaches/train_audio2landmark.py", line 81, in __init__
    with open(os.path.join('examples', 'dump', 'emb.pickle'), 'rb') as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'examples/dump/emb.pickle'

**Comment by bluestyle97** [comment]
@ak9250 Hi, how did you fix the bug "FileNotFoundError: [Errno 2] No such file or directory: 'examples/dump/celeb_withrot_val_au.pickle'"? I meet this bug too.

**Comment by ghost** [comment]
@bluestyle97 just pull the latest change from the fork https://github.com/yzhou359/MakeItTalk
